version: "3.9"
services:
  air:
    container_name: dev_app
    image: cosmtrek/air:v1.28.0
    working_dir: /app
    ports:
      - 3001:3001
    environment:
      - DBPATH=./server.db
      - SRVADRESS=localhost
      - SRVPORT=3001
      - DBNAME=application
    volumes:
      - ./:/app/
  app:
    container_name: app
    build: .
    ports:
      - 3001:3001
    environment:
      - DBPATH=./server.db
      - SRVADRESS=localhost
      - SRVPORT=3001
      - DBNAME=application
    volumes:
      - ./env:/app/.env